### ISSUE TITLE
Manipulating json files leads to inconsistent behaviour

### ISSUE THREAD

**Issue by THuppke** [openbase/bco.registry#4]
Starting the unit-registry after changing unitconfig files leads to strange behaviour.
### **Example 47e63f5a-ff30-4b0d-905a-815f94aa8b50.json (LoungeLamp):**
**Adding a value to any of the fields of "translation" or "rotation" will lead to the following behaviour:**
- The values will be updated in the registry editor.
-- On restart of registry editor, they are reset to 0.0 (/1.0)
- Accessed via java the values remain 0.0
- On closing the unit-registry the json file is reset to the 0.0 values.

**Adding the following part to "shape" will cause the following behaviour:**
```
"bounding_box": {
  "left_front_bottom": {
    "x": 0.0,
    "y": 0.0,
    "z": 1.0
  },
  "width": 1.0,
  "depth": 1.0,
  "height": 0.5
}
```
- Values are updated in the registry editor
-- remain there after restart of registry editor
- Are not accessible via java UnitRegistryRemote
- Remain in the file after closing

**Comment by pLeminoq** [comment]
The reason for the first issue is that you update the "translation" and/or "rotation" in a unit that is bound to its unit host. Thus these values are overridden by a consistency handler which uses the values from the corresponding device. So if the unit is bound to its unit host you have to change these values in the unit host which will automatically change the values in the unit.
The values are displayed in the registry editor because the registry seems to publish its entries before the consistency check is completed and the editor somehow does not receive an update after the consistency check or ignores it.

The reason why the bounding box values are not accessible via UnitRegistryRemote still has to be examined.

**Comment by DivineThreepwood** [comment]
Issue is already outdated, reopen if this error occurs again.
